exports.agenda = [
	"They want someone murdered",
	"They want to make a lot of money",
	"They want to discredit a rival",
	"They want to help a friend or ally in trouble",
	"They want a mystery solved",
	"They want a monster slain",
	"They want to elevate their social standing",
	"They want someone subverted to their cause",
	"They want a crime committed",
	"They want someone to be driven away",
	"They want to obtain a particular object",
	"They want a matter hushed up",
	"To win the love or possession of someone",
	"To obtain riches and personal wealth",
	"To win political power or an particular ofﬁce",
	"To obtain glory or get fame for a skill",
	"To gain a particular property or piece of land",
	"To go to or explore a far-off place",
	"To become a difﬁcult-to-become profession",
	"To kill or ruin a hated rival",
	"To topple an institution, business, or faith",
	"To repay some immeasurable debt"
];

exports.approach = [
	"bargain",
	"direct force",
	"manipulation",
	"begging",
	"bribe/blackmail",
	"ask benefactor",
	"buy problems away",
	"avoidance/denial",
	"aggression/intimidation",
	"acceptance/repression",
	"blame/project onto others",
	"espionage/subterfuge",
	"seek support from a friend/the community",
	"scheme & plot"
];

exports.assets = [
	"A cache of saved or discovered wealth",
	"A useful magical item",
	"A book with critical information in it",
	"A teacher who can impart a great skill",
	"A religious zeal to carry out the ambition",
	"A fortunate coincidence",
	"A sorcerer involved in it somehow",
	"A recent stroke of luck",
	"Someone integral to helping them further it",
	"A magical trait that aids their purpose",
	"Reluctant rival-partner in their ambition"
];

exports.limits = [
	"A jealous “ally” seeking to sabotage them",
	"A loved one who thinks it all folly",
	"An addiction they use to cope with the strain",
	"A patron who needs favors at times",
	"A failed ambition-seeker with bitter jealousy",
	"A rival with no hard feelings toward them",
	"A terribly bad coincidence",
	"A deal they made is coming back to haunt",
	"A recent stroke of bad luck",
	"A crime they committed for their ambition",
	"A mistake which taught them a great deal",
	"A disinterested third party is blocking the way",
	"They've made promises that are coming due",
	"They're burning out a resource in the pursuit",
	"They're physically pushing themselves too far",
	"They suffered a recent considerable setback",
	"A friend or loved one is somehow in the way",
	"A backlash is about to rebound on them",
	"They're chasing the goal in the wrong way",
	"They've been fed some false information",
	"They've lost a critical resource or tool",
	"A traitor is sabotaging their efforts",
	"Their success is bringing hostile attention",
	"There exists grave blackmail on them",
	"They're enamoured of a manipulator",
	"They're a physical coward",
	"They're in serious and pressing debt",
	"A rival is beating them at their own game",
	"They recently made a grave error of judgment",
	"They're lamentably overconfident",
	"Their social standing is being undermined",
	"Someone they love makes horrible choices",
	"An underling plots to betray them"
];
