// by class
exports.underclass = [
	"Black sheep of a gentry family",
	"Cast-off former gentry mistress",
	"Coldly professional criminal",
	"Corrupt petty clerk or guard",
	"Cynical dancing girl or boy",
	"Downfallen former gentry",
	"Foreigner struggling to survive",
	"Gap-toothed local thug",
	"Hardscrabble orphaned urchin",
	"Missionary of an unpopular god",
	"Penniless country boy or girl",
	"Popular actor or actress",
	"Prostitute with a heart of gold",
	"Salt-worn common sailor",
	"Scabby beggar",
	"Shabby boarding-house owner",
	"Shaky-handed slum physician",
	"Slanderous poet or playwright",
	"Thieving drunkard or junkie",
	"Tippling bargeman or boatman",
	"Unpopular but zealous artist",
	"Unpopular demihuman",
	"Weary ragpicker or scavenger",
	"Widely-despised moneylender",
	"Worn-down day laborer"
];
exports.commoners = [
	"Ambitious young entrepreneur",
	"Artisan of some local fame",
	"Butler or servant to a major ﬁgure",
	"Fearfully respected local gossip",
	"Foreigner with enough money",
	"Harried landlord",
	"Herbalist or local healer",
	"Local innkeeper or taverner",
	"Merchant in grain or bulk goods",
	"Merchant on his way down",
	"Military ofﬁcer or guard ofﬁcial",
	"Minor government functionary",
	"Modestly prosperous farmer",
	"Neighborhood shopkeeper",
	"Obsessed local scholar",
	"Peasant like all their neighbors are",
	"Priest of a local faith",
	"Respected local ascetic or hermit",
	"Retired adventurer",
	"Scuffed but respectable laborer",
	"Ship’s captain or ofﬁcer",
	"Someone important’s mistress",
	"Venerable family elder",
	"Veteran soldier or guardsman",
	"Wandering peddler or trader"
];
exports.gentry = [
	"Abbot or head of a monastery",
	"Court wizard or gentry mage",
	"Demihuman leader or high priest",
	"Diplomat from a foreign land",
	"Discreet kingmaker or spymaster",
	"Ethnarch of a local minority",
	"Feared semi-legit criminal boss",
	"Genteelly-kept noble hostage",
	"Kept pretender to a foreign title",
	"Local temple’s high priest",
	"Magistrate or judge",
	"Major local ofﬁcial or minister",
	"Mayor or chief city ofﬁcial",
	"Merchant-prince of wide affairs",
	"Military general or high ofﬁcer",
	"Most popular courtesan in town",
	"Paid-off noble family disgrace",
	"Revered artistic genius",
	"Rusticating loser of a court feud",
	"Ruthless noble clan patriarch",
	"Sorcerer of fearsome name",
	"Spare prince or major noble scion",
	"Traditional cultural ofﬁce-holder",
	"Wealthy but hated usurer",
	"Wealthy scholar-noble"
];

// by role
exports.specificTribals = [
	"Zealous shaman of an obscure god",
	"The most fearsome warrior of the tribe",
	"The tribe’s most eligible maiden or bachelor",
	"Outsider who’s gone native with them",
	"Missionary trying to convert the tribe",
	"Ambitious tribal war leader",
	"Merchant trying to cut a deal with the tribe",
	"Xenophobic tribal elder of great inﬂuence",
	"Keeper of occult tribal secrets",
	"Fabulously talented tribal artisan",
	"Tribal who spent some years out in the world",
	"Sage tribal lorekeeper or historian"
];
exports.specificWarriors = [
	"Bronze-thewed barbarian giant",
	"Coldly pragmatic bandit chief",
	"Hard-bitten and cynical mercenary sword",
	"Skulking archer-sniper favoring stealth",
	"Determinedly foppish duelist",
	"Philosophical-minded village militiaman",
	"Proudly skilled longbowman",
	"Consecrated temple defender or crusader",
	"Cunning thug or hired enforcer",
	"Foreigner bearing a strange weapon",
	"Nondescript hired killer",
	"Serial killer under thin societal justiﬁcation"
];
exports.specificVillagers = [
	"Biggest and cleverest bully in the village",
	"Maiden or boy of known easy virtue",
	"Restless youth who yearns to roam afar",
	"Best farmer in all the hundred",
	"Half-feral shepherd or swineherd",
	"Village priest of phlegmatic temperament",
	"Local artisan of considerable talent",
	"Urban gentry resenting forced rustication",
	"Local wise woman or cunning man",
	"Canny local headman or mayor",
	"Reeve serving the village’s lord",
	"Traveler stuck here for some reason"
];
exports.specificMerchants = [
	"Grasping usurer with a long list of debts",
	"Trader in exotic and potentially illegal wares",
	"Ambitious young merchant on their way up",
	"Major landlord in the area",
	"Monopolist with a royal patent for it",
	"Brutally competitive merchant-thug",
	"Cartel boss with plenty of enforcers",
	"Supplier of arms or goods to the government",
	"Wandering peddler or roaming merchant",
	"Ship-owner or trader with far lands",
	"Plantation owner or sharecropper master",
	"Desperate oligarch with crumbling assets"
];
exports.specificNobility = [
	"Royal scion judged unﬁt for responsibility",
	"Merchant-noble who bought their title",
	"Head of a minor but very respected house",
	"Heir to a major local noble title",
	"Fallen foreign noble in safe exile here",
	"Scheming lesser noble with grand ideas",
	"Noble on their way down from bad choices",
	"Court favorite with greater ambitions",
	"Treacherous but trusted noble plotter",
	"Idealistic and well-meaning young ruler",
	"Grizzled noble who earned their title in war",
	"House leader who’s getting too old for this"
];
exports.specificCriminals = [
	"Decadent noble turned crime boss for fun",
	"Obsessively driven underclass-turned-capo",
	"Psychopathically indifferent assassin",
	"Notorious cat burglar",
	"Infamously slippery con man",
	"Wealthy madame with vast blackmail ﬁles",
	"Terrifyingly brutal gang boss",
	"Local protector of the poor for a proﬁt",
	"Smuggler dealing in very illegal wares",
	"Renegade mage meddling with dark powers",
	"Noble ofﬁcial robbing under color of law",
	"Master spy for hire by the wealthy"
];

// twists
exports.npcCharacteristicTwists = [
	"They’re abnormally rich or poor for their class",
	"They are extremely averse to using violence",
	"They tend to break their deals, wisely or not",
	"They have a reason to hate people like the PC",
	"They have a useful but unusual friend",
	"The PC or an ally owes them a debt",
	"A disaster is looming rapidly for them",
	"They have a reason to like people like the PC",
	"They’ve got few reliable local social ties",
	"They conceal a socially-lethal secret",
	"They’re an ex-convict or former underclass",
	"They have a secret identity"
];