exports.appearance = require("./WWN/NPCs/appearance");
exports.burningAmbition = require("./WWN/NPCs/burning ambitions");
exports.closeFriendships = require("./WWN/NPCs/close friendships");
exports.personalTragedies = require("./WWN/NPCs/personal tragedies");
exports.troubledRomances = require("./WWN/NPCs/troubled romances");
exports.names = require("./names");
exports.customTables = require("./customTables");
exports.genericStats = require("./WWN/NPCs/generic stats");
exports.npcTypes = require("./WWN/NPCs/npc types");
